# kyber_module.py

"""
Kyber Module using kyber-py

This module provides a wrapper for the CRYSTALS-Kyber implementation
using all parameter sets (Kyber512, Kyber768, Kyber1024) from the kyber-py package.
Each function accepts a security_level parameter to specify which variant to use:
  - 512: 128-bit security level
  - 768: 192-bit security level
  - 1024: 256-bit security level
"""

from kyber_py.kyber import Kyber512, Kyber768, Kyber1024

KYBER_VARIANTS = {
    512: Kyber512,
    768: Kyber768,
    1024: Kyber1024
}

def get_kyber_instance(security_level=512):
    """
    Get the appropriate Kyber instance based on security level.
    
    Args:
        security_level (int): 512, 768, or 1024
        
    Returns:
        Kyber instance
        
    Raises:
        ValueError: If security_level is not valid
    """
    if security_level not in KYBER_VARIANTS:
        raise ValueError(f"Invalid security level. Must be one of: {list(KYBER_VARIANTS.keys())}")
    return KYBER_VARIANTS[security_level]

def kyber_keygen(security_level=512):
    """
    Generate a CRYSTALS-Kyber key pair using the specified parameter set.
    
    Args:
        security_level (int): 512 (128-bit security), 768 (192-bit security), or 1024 (256-bit security)
    
    Returns:
        tuple: (public_key, secret_key) as bytes.
    """
    kyber = get_kyber_instance(security_level)
    public_key, secret_key = kyber.keygen()
    return public_key, secret_key

def kyber_encapsulate(public_key, security_level=512):
    """
    Encapsulate a shared secret using the CRYSTALS-Kyber public key.
    
    Args:
        public_key (bytes): The public key generated by kyber_keygen().
        security_level (int): 512, 768, or 1024
    
    Returns:
        tuple: (ciphertext, shared_secret) as bytes.
    """
    kyber = get_kyber_instance(security_level)
    shared_secret, ciphertext = kyber.encaps(public_key)
    return ciphertext, shared_secret

def kyber_decapsulate(secret_key, ciphertext, security_level=512):
    """
    Decapsulate the ciphertext using the CRYSTALS-Kyber secret key to recover the shared secret.
    
    Args:
        secret_key (bytes): The secret key generated by kyber_keygen().
        ciphertext (bytes): The ciphertext from encapsulation.
        security_level (int): 512, 768, or 1024
    
    Returns:
        bytes: The recovered shared secret.
    """
    kyber = get_kyber_instance(security_level)
    shared_secret = kyber.decaps(secret_key, ciphertext)
    return shared_secret

# For demonstration purposes: run a test when executed directly.
if __name__ == '__main__':
    for security_level in [512, 768, 1024]:
        print(f"\nTesting Kyber{security_level}...")
        print("Generating Key Pair...")
        pk, sk = kyber_keygen(security_level)
        print(f"Public Key Length: {len(pk)}")
        print(f"Secret Key Length: {len(sk)}")
        
        print("\nEncapsulating Shared Secret...")
        ct, ss_enc = kyber_encapsulate(pk, security_level)
        print(f"Ciphertext Length: {len(ct)}")
        print(f"Encapsulated Shared Secret Length: {len(ss_enc)}")
        print(f"Ciphertext (first 32 bytes): {ct[:32].hex()}")
        
        print("\nDecapsulating to Recover Shared Secret...")
        try:
            ss_dec = kyber_decapsulate(sk, ct, security_level)
            if ss_enc == ss_dec:
                print("Shared secrets match.")
            else:
                print("Error: Shared secrets do not match.")
        except ValueError as e:
            print("Error during decapsulation:", str(e))
